"""added relationship owner to Sorteo_SC

Revision ID: 49405629cd4b
Revises: efe90f3848a0
Create Date: 2023-06-24 13:30:42.761913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49405629cd4b'
down_revision = 'efe90f3848a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
