"""auto-table

Revision ID: 4b0483c18906
Revises: 
Create Date: 2023-06-24 14:22:41.969600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b0483c18906'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=True),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('fecha_cumple', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('rifas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jugador', sa.String(), nullable=False),
    sa.Column('telefono', sa.String(), nullable=False),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lugar_registro', sa.String(), nullable=False),
    sa.Column('en_sorteo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('premios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=False),
    sa.Column('descuento', sa.Integer(), nullable=True),
    sa.Column('auspiciante', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('imagen_url', sa.String(length=500), nullable=True),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('en_sorteo', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premios_imagen_url'), 'premios', ['imagen_url'], unique=False)
    op.create_table('sorteos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rifas_id', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('premios_id', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('sorteado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('premios_id'),
    sa.UniqueConstraint('rifas_id')
    )
    op.create_table('sorteos_realizados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rifas_id', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('premios_id', sa.ARRAY(sa.Integer()), nullable=False),
    sa.Column('fecha_registro', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_sorteo', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lugar_sorteo', sa.String(), nullable=False),
    sa.Column('auspciante', sa.String(), nullable=False),
    sa.Column('contacto', sa.String(), nullable=False),
    sa.Column('ganadores', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['premios_id'], ['sorteos.premios_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rifas_id'], ['sorteos.rifas_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sorteos_realizados')
    op.drop_table('sorteos')
    op.drop_index(op.f('ix_premios_imagen_url'), table_name='premios')
    op.drop_table('premios')
    op.drop_table('users')
    op.drop_table('rifas')
    op.drop_table('clientes')
    # ### end Alembic commands ###
