"""added user_id in Sorteo_SC so it has a relationship with owner

Revision ID: 8c8132605baa
Revises: 49405629cd4b
Create Date: 2023-06-24 13:36:57.856329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c8132605baa'
down_revision = '49405629cd4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sorteos_realizados', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sorteos_realizados', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sorteos_realizados', type_='foreignkey')
    op.drop_column('sorteos_realizados', 'user_id')
    # ### end Alembic commands ###
