"""remove cantidad column from Premio model

Revision ID: efe90f3848a0
Revises: 8de0985825df
Create Date: 2023-06-24 12:30:37.676794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efe90f3848a0'
down_revision = '8de0985825df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premios', 'cantidad')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premios', sa.Column('cantidad', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
